version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    ports:
      - 8089:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/date_calculation
      - SPRINT_DATASOURCE_USERNAME=user
      - SPRINT_DATASOURCE_PASSWORD=example
    depends_on:
      - db
  db:
    platform: linux/x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: date_calculation
      MYSQL_USER: user
      MYSQL_PASSWORD: example
      TZ: "Asia/Tokyo"
    ports:
      - 3307:3306
    volumes:
      - $PWD/sql:/docker-entrypoint-initdb.d
      - $PWD/conf/mysql:/etc/mysql/conf.d
